### ISSUE TITLE
Internal Server Error for the CSV File and JSON data

### ISSUE THREAD

**Issue by gautamsarawagi** [Sage-Bionetworks/schema_visualization#24]
The visualize/tangled_tress/layers API not working: 

![image](https://github.com/Sage-Bionetworks/schema_visualization/assets/101802666/11de7b81-6aef-480d-96eb-e8bc5b447635)

Resulting in a blank page:

![image](https://github.com/Sage-Bionetworks/schema_visualization/assets/101802666/a74fb7d6-22bc-4ed2-9717-7ef5cf953096)

**Comment by andrewelamb** [comment]
@gautamsarawagi Could you try switching the data model URL to "https://raw.githubusercontent.com/Sage-Bionetworks/schematic/main/tests/data/example.model.jsonld"?

**Comment by gautamsarawagi** [comment]
@andrewelamb it worked.
